sudo: required
services:
  - docker

before_install:
  - docker build -t ramonnuns/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ramonnuns/react-test npm test

after_success:
  - docker build -t ramonnuns/multi-client ./client
  - docker build -t ramonnuns/multi-nginx ./nginx
  - docker build -t ramonnuns/multi-server ./server
  - docker build -t ramonnuns/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ramonnuns/multi-client
  - docker push ramonnuns/multi-nginx
  - docker push ramonnuns/multi-server
  - docker push ramonnuns/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-335154013629"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY