version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
  redis:
    image: 'redis:latest'
    restart: always
  api:
    build: 
      context: ./server  
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST= "${REDIS_HOST}"
      - REDIS_PORT= "${REDIS_PORT}"  
      - PGUSER= "${PGUSER}"
      - PGHOST= "${PGHOST}"
      - PGDATABASE= "${PGDATABASE}"
      - PGPASSWORD= "${PGPASSWORD}"
      - PGPORT= "${PGPORT}"
    ports:
      - '5000:5000'    