version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
  redis:
    image: 'redis:latest'
    restart: always
  nginx:
    restart: always
    depends_on:
      - api
      - client
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  api:
    build: 
      context: ./server  
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST= "${REDIS_HOST}"
      - REDIS_PORT= "${REDIS_PORT}"  
      - PGUSER= "${PGUSER}"
      - PGHOST= "${PGHOST}"
      - PGDATABASE= "${PGDATABASE}"
      - PGPASSWORD= "${PGPASSWORD}"
      - PGPORT= "${PGPORT}"
  client:
    stdin_open: true
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST= "${REDIS_HOST}"
      - REDIS_PORT= "${REDIS_PORT}"   